klarna/klarna-mobile-sdk

CHANGELOG.md
Added changelog records for 2.0.13 and 2.0.14
=> Android changelog 2.0.13 - 2.0.14

BUILD_VARIANTS_README.md
update BUILD_VARIANTS_README to the latest version.
=> BUILD_VARIANTS_README was updated to the current version.

CHANGELOG.md, KlarnaPaymentsAndroid.md
Fixed an issue with the `Context` instance being used to move or create separate web views.
=> Android 2.0.17

CHANGELOG.md, KlarnaPaymentsAndroid.md
Update changelog and android documentation spec.
=> Android 2.0.19

CHANGELOG.md, README.md
Improved the readme text and updated the changelog
=> reviewed the readme file and improved the text

CHANGELOG.md
Android release 2.0.23 and missing changelogs
=> Android Release 2.0.23

CHANGELOG.md
Android 2.0.24 release changelogs
=> add changelog for android 2.0.24 release

CHANGELOG.md
Android SDK v2.0.27 is released.
=> Changelog for Android 2.0.27 Release

CHANGELOG.md
Android SDK v2.0.28 is released.
=> Android 2.0.28 Release

CHANGELOG.md
=> Android 2.0.32 Release

CHANGELOG.md
=> Android 2.0.33 Release

CHANGELOG.md
2.0.35 release notes
Warning for the previous release
=> Android 2.0.35 Release

CHANGELOG.md
=> Android 2.0.36 Release

CHANGELOG.md
=> Android 2.0.39 Release

CHANGELOG.md
=> Android 2.0.40 Release

CHANGELOG.md
Added changelog regarding basic/full switch for the default SDK
=> Android 2.0.41 Release

CHANGELOG.md
=> Android 2.1.6 release

CHANGELOG.md
=> Android v2.6.14 change log

CHANGELOG.md, KlarnaMobileSDK.json, KlarnaMobileSDK.podspec, Package.swift
New Klarna Mobile SDK iOS version: 2.7.1
=> Release Klarna Mobile SDK iOS v2.7.1

CHANGELOG.md, KlarnaMobileSDK.podspec, Package.swift
New Klarna Mobile SDK iOS version: 2.7.3
=> Release Klarna Mobile SDK iOS v2.7.3
